### ISSUE TITLE
Odd formatting decision with parenthesized function call with attrset

### ISSUE THREAD

**Issue by emilazy** [nix-community/nixpkgs-fmt#178]
## Input
```nix
{
  nixpkgs-fmt = (buildCargoCrate {
    name = "nixpkgs-fmt";
    # TODO: probably want to filter .gitignore or something
    src = sources.nixpkgs-fmt;
  }).nixpkgs-fmt.build;
}
```

## Output
```nix
{
  nixpkgs-fmt = (buildCargoCrate {
    name = "nixpkgs-fmt";
    # TODO: probably want to filter .gitignore or something
    src = sources.nixpkgs-fmt;
  }
  ).nixpkgs-fmt.build;
}
```

## Desired output

I personally find the original less odd-looking here, and this seems to be one of the few cases where I disagree with nixpkgs-fmt's decision. Sorry if this has already been opened/discussed; I couldn't find anything from a brief search of the issue tracker.

**Comment by zimbatm** [comment]
@emilazy agreed. We are still refining the formatting output so thanks for bringing that up!

**Comment by Rizary** [comment]
@emilazy following to #180, I try to make user decide to have newline after open parentheses or before closed parentheses. So in your above example, it should be fixed now.

**Comment by emilazy** [comment]
Still experiencing this even after those commits and #182, unfortunately. Minimum reproducible example:

```nix
(foo {
  inherit bar;
})
```

**Comment by Rizary** [comment]
Oh my bad! Actually I think it is about this line:
https://github.com/Rizary/nixpkgs-fmt/blob/2f04be1252c1996ae358f44552bab5705ed126d5/src/rules.rs#L73

Because the parentheses is in top level. Actually is not needed anymore
after latest PR.

I just off from my computer, I'll take a look couple hours later.

Thank you!

**Comment by Rizary** [comment]
@emilazy the above issue fixed in #183
